# create a data frame from Altman's financial data for Dillards dept store

In [33]:
# https://www.sec.gov/dera/data/financial-statement-data-sets.html
import os
import pandas as pd
import numpy as np
from re import search

# 0000028917-25-000032	28917	DILLARD'S, INC.	5311	US	AR	LITTLE ROCK	72201	1600 CANTRELL RD		5013765200	US	AR	LITTLE ROCK	72201	1600 CANTRELL ROAD		US	TX	710388071	DILLARDS INC	19980622	1-LAF	0	0131	10-Q	20251031	2025	Q3	20251205	2025-12-05 16:46:00.0	0	1	dds-20251101x10q_htm.xml	1

num_target = "0000028917-25-000032" #"0000028917-20-000127"
dirname = "2025q4"

d = pd.read_csv(os.path.join(dirname,file[2]), sep='\t')
d.head(3)

,adsh,cik,name,sic,countryba,stprba,cityba,zipba,bas1,bas2,...,period,fy,fp,filed,accepted,prevrpt,detail,instance,nciks,aciks
0,0000002488-25-000166,2488,ADVANCED MICRO DEVICES INC,3674.0,US,CA,SANTA CLARA,95054,2485 AUGUSTINE DRIVE,NaN,...,20250930,2025.0,Q3,20251105,2025-11-04 18:08:00.0,0,1,amd-20250927_htm.xml,1,NaN
1,0000002969-25-000055,2969,"AIR PRODUCTS & CHEMICALS, INC.",2810.0,US,PA,ALLENTOWN,18106-5500,1940 AIR PRODUCTS BLVD.,NaN,...,20250930,2025.0,FY,20251120,2025-11-20 10:21:00.0,0,1,apd-20250930_htm.xml,1,NaN
2,0000003499-25-000026,3499,ALEXANDERS INC,6798.0,US,NJ,PARAMUS,07652,210 ROUTE 4 EAST,NaN,...,20250930,2025.0,Q3,20251103,2025-11-03 08:42:00.0,0,1,alx-20250930_htm.xml,1,NaN

In [34]:
company_name = "DILLARD'S, INC."
company = d[d['name'] == company_name]
num_target = company['adsh'].tolist()[0]
print(f"{num_target = }")
company

num_target = '0000028917-25-000032'

,adsh,cik,name,sic,countryba,stprba,cityba,zipba,bas1,bas2,...,period,fy,fp,filed,accepted,prevrpt,detail,instance,nciks,aciks
68,0000028917-25-000032,28917,"DILLARD'S, INC.",5311.0,US,AR,LITTLE ROCK,72201,1600 CANTRELL RD,NaN,...,20251031,2025.0,Q3,20251205,2025-12-05 16:46:00.0,0,1,dds-20251101x10q_htm.xml,1,NaN

In [35]:
with open(os.path.join(dirname,file[0]), 'r') as f:
    d = f.readlines()

In [36]:
print(len(d))
d0 = [t for t in d if search("^"+ num_target, t)]
d0

3832978

['0000028917-25-000032\tAccountsPayableAndAccruedLiabilitiesCurrent\tus-gaap/2024\t20241031\t0\tUSD\t\t\t1214982000.0000\t\n',
 '0000028917-25-000032\tAccountsPayableAndAccruedLiabilitiesCurrent\tus-gaap/2024\t20250131\t0\tUSD\t\t\t795023000.0000\t\n',
 '0000028917-25-000032\tAccountsPayableAndAccruedLiabilitiesCurrent\tus-gaap/2024\t20251031\t0\tUSD\t\t\t1213976000.0000\t\n',
 '0000028917-25-000032\tAccountsReceivableNetCurrent\tus-gaap/2024\t20241031\t0\tUSD\t\t\t61741000.0000\t\n',
 '0000028917-25-000032\tAccountsReceivableNetCurrent\tus-gaap/2024\t20250131\t0\tUSD\t\t\t55700000.0000\t\n',
 '0000028917-25-000032\tAccountsReceivableNetCurrent\tus-gaap/2024\t20251031\t0\tUSD\t\t\t44901000.0000\t\n',
 '0000028917-25-000032\tAccruedIncomeTaxesCurrent\tus-gaap/2024\t20241031\t0\tUSD\t\t\t10030000.0000\t\n',
 '0000028917-25-000032\tAccruedIncomeTaxesCurrent\tus-gaap/2024\t20250131\t0\tUSD\t\t\t28472000.0000\t\n',
 '0000028917-25-000032\tAccruedIncomeTaxesCurrent\tus-gaap/2024\t20251031\t0\tUSD\t\t\t125443000.0000\t\n',
 '0000028917-25-000032\tAccruedTreasuryStockPurchases\t0000028917-25-000032\t20241031\t3\tUSD\t\t\t3053000.0000\t\n',
 '0000028917-25-000032\tAccruedTreasuryStockPurchases\t0000028917-25-000032\t20251031\t3\tUSD\t\t\t1064000.0000\t\n',
 '0000028917-25-000032\tAccumulatedDepreciationDepletionAndAmortizationPropertyPlantAndEquipment\tus-gaap/2024\t20241031\t0\tUSD\t\t\t2769402000.0000\t\n',
 '0000028917-25-000032\tAccumulatedDepreciationDepletionAndAmortizationPropertyPlantAndEquipment\tus-gaap/2024\t20250131\t0\tUSD\t\t\t2774081000.0000\t\n',
 '0000028917-25-000032\tAccumulatedDepreciationDepletionAndAmortizationPropertyPlantAndEquipment\tus-gaap/2024\t20251031\t0\tUSD\t\t\t2882759000.0000\t\n',
 '0000028917-25-000032\tAccumulatedOtherComprehensiveIncomeLossNetOfTax\tus-gaap/2024\t20241031\t0\tUSD\t\t\t-81376000.0000\t\n',
 '0000028917-25-000032\tAccumulatedOtherComprehensiveIncomeLossNetOfTax\tus-gaap/2024\t20250131\t0\tUSD\t\t\t-49851000.0000\t\n',
 '0000028917-25-000032\tAccumulatedOtherComprehensiveIncomeLossNetOfTax\tus-gaap/2024\t20251031\t0\tUSD\t\t\t-47427000.0000\t\n',
 '0000028917-25-000032\tAdditionalPaidInCapitalCommonStock\tus-gaap/2024\t20241031\t0\tUSD\t\t\t968909000.0000\t\n',
 '0000028917-25-000032\tAdditionalPaidInCapitalCommonStock\tus-gaap/2024\t20250131\t0\tUSD\t\t\t971524000.0000\t\n',
 '0000028917-25-000032\tAdditionalPaidInCapitalCommonStock\tus-gaap/2024\t20251031\t0\tUSD\t\t\t972855000.0000\t\n',
 '0000028917-25-000032\tAssets\tus-gaap/2024\t20241031\t0\tUSD\t\t\t4133062000.0000\t\n',
 '0000028917-25-000032\tAssets\tus-gaap/2024\t20241031\t0\tUSD\tBusinessSegments=ConstructionSegment;ConsolidationItems=OperatingSegments;\t\t79356000.0000\t\n',
 '0000028917-25-000032\tAssets\tus-gaap/2024\t20241031\t0\tUSD\tBusinessSegments=RetailOperationsSegment;ConsolidationItems=OperatingSegments;\t\t4053706000.0000\t\n',
 '0000028917-25-000032\tAssets\tus-gaap/2024\t20250131\t0\tUSD\t\t\t3531054000.0000\t\n',
 '0000028917-25-000032\tAssets\tus-gaap/2024\t20251031\t0\tUSD\t\t\t4298065000.0000\t\n',
 '0000028917-25-000032\tAssets\tus-gaap/2024\t20251031\t0\tUSD\tBusinessSegments=ConstructionSegment;ConsolidationItems=OperatingSegments;\t\t73465000.0000\t\n',
 '0000028917-25-000032\tAssets\tus-gaap/2024\t20251031\t0\tUSD\tBusinessSegments=RetailOperationsSegment;ConsolidationItems=OperatingSegments;\t\t4224600000.0000\t\n',
 '0000028917-25-000032\tAssetsCurrent\tus-gaap/2024\t20241031\t0\tUSD\t\t\t2942301000.0000\t\n',
 '0000028917-25-000032\tAssetsCurrent\tus-gaap/2024\t20250131\t0\tUSD\t\t\t2368070000.0000\t\n',
 '0000028917-25-000032\tAssetsCurrent\tus-gaap/2024\t20251031\t0\tUSD\t\t\t3169032000.0000\t\n',
 '0000028917-25-000032\tCapitalExpendituresIncurredButNotYetPaid\tus-gaap/2024\t20241031\t3\tUSD\t\t\t9935000.0000\t\n',
 '0000028917-25-000032\tCapitalExpendituresIncurredButNotYetPaid\tus-gaap/2024\t20251031\t3\tUSD\t\t\t9824000.0000\t\n',
 '0000028917-25-000032\tCashAndCashEquivalentsAtCarryingValue\tus-gaap/2024\t20241031\t0\tUSD\t\t\t980392000.0000\t\n',
 '0000028917-25-000032\tCashAndCashEquivalentsAtCarryingValue\tus-gaap/2024\t20250131\t0\tUSD\t\t\t717854000.0000\t\n',
 '0000028917-25-000032\tCashAndCashEquivalentsAtCarryingValue\tus-gaap/2024\t20251031\t0\tUSD\t\t\t1149201000.0000\t\n',
 '0000028917-25-000032\tCashCashEquivalentsRestrictedCashAndRestrictedCashEquivalents\tus-gaap/2024\t20240131\t0\tUSD\t\t\t808287000.0000\t\n',
 '0000028917-25-000032\tCashCashEquivalentsRestrictedCashAndRestrictedCashEquivalents\tus-gaap/2024\t20241031\t0\tUSD\t\t\t980392000.0000\t\n',
 '0000028917-25-000032\tCashCashEquivalentsRestrictedCashAndRestrictedCashEquivalents\tus-gaap/2024\t20250131\t0\tUSD\t\t\t717854000.0000\t\n',
 '0000028917-25-000032\tCashCashEquivalentsRestrictedCashAndRestrictedCashEquivalents\tus-gaap/2024\t20251031\t0\tUSD\t\t\t1149201000.0000\t\n',
 '0000028917-25-000032\tCashCashEquivalentsRestrictedCashAndRestrictedCashEquivalentsPeriodIncreaseDecreaseExcludingExchangeRateEffect\tus-gaap/2024\t20241031\t3\tUSD\t\t\t172105000.0000\t\n',
 '0000028917-25-000032\tCashCashEquivalentsRestrictedCashAndRestrictedCashEquivalentsPeriodIncreaseDecreaseExcludingExchangeRateEffect\tus-gaap/2024\t20251031\t3\tUSD\t\t\t431347000.0000\t\n',
 '0000028917-25-000032\tCommitmentsAndContingencies\tus-gaap/2024\t20241031\t0\tUSD\t\t\t\t\n',
 '0000028917-25-000032\tCommitmentsAndContingencies\tus-gaap/2024\t20250131\t0\tUSD\t\t\t\t\n',
 '0000028917-25-000032\tCommitmentsAndContingencies\tus-gaap/2024\t20251031\t0\tUSD\t\t\t\t\n',
 '0000028917-25-000032\tCommonStockDividendsPerShareDeclared\tus-gaap/2024\t20241031\t1\tUSD\t\t\t0.2500\t\n',
 '0000028917-25-000032\tCommonStockDividendsPerShareDeclared\tus-gaap/2024\t20241031\t3\tUSD\t\t\t0.7500\t\n',
 '0000028917-25-000032\tCommonStockDividendsPerShareDeclared\tus-gaap/2024\t20251031\t1\tUSD\t\t\t0.3000\t\n',
 '0000028917-25-000032\tCommonStockDividendsPerShareDeclared\tus-gaap/2024\t20251031\t3\tUSD\t\t\t0.8000\t\n',
 '0000028917-25-000032\tCommonStockDividendsPerShareDeclared\tus-gaap/2024\t20251130\t0\tUSD\tClassOfStock=CommonClassA;Dividends=S2025Dividends;SubsequentEventType=SubsequentEvent;\t\t30.0000\t\n',
 '0000028917-25-000032\tCommonStockDividendsPerShareDeclared\tus-gaap/2024\t20251130\t0\tUSD\tClassOfStock=CommonClassB;Dividends=S2025Dividends;SubsequentEventType=SubsequentEvent;\t\t30.0000\t\n',
 '0000028917-25-000032\tCommonStockValue\tus-gaap/2024\t20241031\t0\tUSD\t\t\t1240000.0000\t\n',
 '0000028917-25-000032\tCommonStockValue\tus-gaap/2024\t20250131\t0\tUSD\t\t\t1241000.0000\t\n',
 '0000028917-25-000032\tCommonStockValue\tus-gaap/2024\t20251031\t0\tUSD\t\t\t1241000.0000\t\n',
 '0000028917-25-000032\tComprehensiveIncomeNetOfTax\tus-gaap/2024\t20241031\t1\tUSD\t\t\t126541000.0000\t\n',
 '0000028917-25-000032\tComprehensiveIncomeNetOfTax\tus-gaap/2024\t20241031\t3\tUSD\t\t\t384949000.0000\t\n',
 '0000028917-25-000032\tComprehensiveIncomeNetOfTax\tus-gaap/2024\t20251031\t1\tUSD\t\t\t130618000.0000\t\n',
 '0000028917-25-000032\tComprehensiveIncomeNetOfTax\tus-gaap/2024\t20251031\t3\tUSD\t\t\t368886000.0000\t\n',
 '0000028917-25-000032\tCostOfRevenue\tus-gaap/2024\t20241031\t1\tUSD\t\t\t819313000.0000\t\n',
 '0000028917-25-000032\tCostOfRevenue\tus-gaap/2024\t20241031\t1\tUSD\tBusinessSegments=ConstructionSegment;ConsolidationItems=OperatingSegments;\t\t66553000.0000\t\n',
 '0000028917-25-000032\tCostOfRevenue\tus-gaap/2024\t20241031\t1\tUSD\tBusinessSegments=RetailOperationsSegment;ConsolidationItems=OperatingSegments;\t\t752760000.0000\t\n',
 '0000028917-25-000032\tCostOfRevenue\tus-gaap/2024\t20241031\t3\tUSD\t\t\t2607469000.0000\t\n',
 '0000028917-25-000032\tCostOfRevenue\tus-gaap/2024\t20241031\t3\tUSD\tBusinessSegments=ConstructionSegment;ConsolidationItems=OperatingSegments;\t\t182018000.0000\t\n',
 '0000028917-25-000032\tCostOfRevenue\tus-gaap/2024\t20241031\t3\tUSD\tBusinessSegments=RetailOperationsSegment;ConsolidationItems=OperatingSegments;\t\t2425451000.0000\t\n',
 '0000028917-25-000032\tCostOfRevenue\tus-gaap/2024\t20251031\t1\tUSD\t\t\t831643000.0000\t\n',
 '0000028917-25-000032\tCostOfRevenue\tus-gaap/2024\t20251031\t1\tUSD\tBusinessSegments=ConstructionSegment;ConsolidationItems=OperatingSegments;\t\t64982000.0000\t\n',
 '0000028917-25-000032\tCostOfRevenue\tus-gaap/2024\t20251031\t1\tUSD\tBusinessSegments=RetailOperationsSegment;ConsolidationItems=OperatingSegments;\t\t766661000.0000\t\n',
 '0000028917-25-000032\tCostOfRevenue\tus-gaap/2024\t20251031\t3\tUSD\t\t\t2648640000.0000\t\n',
 '0000028917-25-000032\tCostOfRevenue\tus-gaap/2024\t20251031\t3\tUSD\tBusinessSegments=ConstructionSegment;ConsolidationItems=OperatingSegments;\t\t186389000.0000\t\n',
 '0000028917-25-000032\tCostOfRevenue\tus-gaap/2024\t20251031\t3\tUSD\tBusinessSegments=RetailOperationsSegment;ConsolidationItems=OperatingSegments;\t\t2462251000.0000\t\n',
 '0000028917-25-000032\tDebtInstrumentIncreaseAccruedInterest\tus-gaap/2024\t20241031\t3\tUSD\t\t\t9253000.0000\t\n',
 '0000028917-25-000032\tDebtInstrumentIncreaseAccruedInterest\tus-gaap/2024\t20251031\t3\tUSD\t\t\t6971000.0000\t\n',
 '0000028917-25-000032\tDebtSecuritiesHeldToMaturityAmortizedCostAfterAllowanceForCreditLossCurrent\tus-gaap/2024\t20241031\t0\tUSD\t\t\t128875000.0000\t\n',
 '0000028917-25-000032\tDebtSecuritiesHeldToMaturityAmortizedCostAfterAllowanceForCreditLossCurrent\tus-gaap/2024\t20250131\t0\tUSD\t\t\t325675000.0000\t\n',
 '0000028917-25-000032\tDebtSecuritiesHeldToMaturityAmortizedCostAfterAllowanceForCreditLossCurrent\tus-gaap/2024\t20251031\t0\tUSD\t\t\t185243000.0000\t\n',
 '0000028917-25-000032\tDeferredIncomeTaxAssetsNet\tus-gaap/2024\t20241031\t0\tUSD\t\t\t64733000.0000\t\n',
 '0000028917-25-000032\tDeferredIncomeTaxAssetsNet\tus-gaap/2024\t20250131\t0\tUSD\t\t\t69099000.0000\t\n',
 '0000028917-25-000032\tDeferredIncomeTaxAssetsNet\tus-gaap/2024\t20251031\t0\tUSD\t\t\t65622000.0000\t\n',
 '0000028917-25-000032\tDepreciationAndAmortization\tus-gaap/2024\t20241031\t1\tUSD\t\t\t44045000.0000\t\n',
 '0000028917-25-000032\tDepreciationAndAmortization\tus-gaap/2024\t20241031\t1\tUSD\tBusinessSegments=ConstructionSegment;ConsolidationItems=OperatingSegments;\t\t69000.0000\t\n',
 '0000028917-25-000032\tDepreciationAndAmortization\tus-gaap/2024\t20241031\t1\tUSD\tBusinessSegments=RetailOperationsSegment;ConsolidationItems=OperatingSegments;\t\t43976000.0000\t\n',
 '0000028917-25-000032\tDepreciationAndAmortization\tus-gaap/2024\t20241031\t3\tUSD\t\t\t136540000.0000\t\n',
 '0000028917-25-000032\tDepreciationAndAmortization\tus-gaap/2024\t20241031\t3\tUSD\tBusinessSegments=ConstructionSegment;ConsolidationItems=OperatingSegments;\t\t300000.0000\t\n',
 '0000028917-25-000032\tDepreciationAndAmortization\tus-gaap/2024\t20241031\t3\tUSD\tBusinessSegments=RetailOperationsSegment;ConsolidationItems=OperatingSegments;\t\t136240000.0000\t\n',
 '0000028917-25-000032\tDepreciationAndAmortization\tus-gaap/2024\t20251031\t1\tUSD\t\t\t44375000.0000\t\n',
 '0000028917-25-000032\tDepreciationAndAmortization\tus-gaap/2024\t20251031\t1\tUSD\tBusinessSegments=ConstructionSegment;ConsolidationItems=OperatingSegments;\t\t83000.0000\t\n',
 '0000028917-25-000032\tDepreciationAndAmortization\tus-gaap/2024\t20251031\t1\tUSD\tBusinessSegments=RetailOperationsSegment;ConsolidationItems=OperatingSegments;\t\t44292000.0000\t\n',
 '0000028917-25-000032\tDepreciationAndAmortization\tus-gaap/2024\t20251031\t3\tUSD\t\t\t133519000.0000\t\n',
 '0000028917-25-000032\tDepreciationAndAmortization\tus-gaap/2024\t20251031\t3\tUSD\tBusinessSegments=ConstructionSegment;ConsolidationItems=OperatingSegments;\t\t237000.0000\t\n',
 '0000028917-25-000032\tDepreciationAndAmortization\tus-gaap/2024\t20251031\t3\tUSD\tBusinessSegments=RetailOperationsSegment;ConsolidationItems=OperatingSegments;\t\t133282000.0000\t\n',
 '0000028917-25-000032\tDepreciationAndAmortizationOfPropertyAndOtherDeferredCosts\t0000028917-25-000032\t20241031\t3\tUSD\t\t\t137817000.0000\t\n',
 '0000028917-25-000032\tDepreciationAndAmortizationOfPropertyAndOtherDeferredCosts\t0000028917-25-000032\t20251031\t3\tUSD\t\t\t134650000.0000\t\n',
 '0000028917-25-000032\tDividendsCommonStockCash\tus-gaap/2024\t20241031\t1\tUSD\t\t\t4019000.0000\t\n',
 '0000028917-25-000032\tDividendsCommonStockCash\tus-gaap/2024\t20241031\t1\tUSD\tEquityComponents=RetainedEarnings;\t\t4019000.0000\t\n',
 '0000028917-25-000032\tDividendsCommonStockCash\tus-gaap/2024\t20241031\t3\tUSD\t\t\t12135000.0000\t\n',
 '0000028917-25-000032\tDividendsCommonStockCash\tus-gaap/2024\t20241031\t3\tUSD\tEquityComponents=RetainedEarnings;\t\t12135000.0000\t\n',
 '0000028917-25-000032\tDividendsCommonStockCash\tus-gaap/2024\t20251031\t1\tUSD\t\t\t4684000.0000\t\n',
 '0000028917-25-000032\tDividendsCommonStockCash\tus-gaap/2024\t20251031\t1\tUSD\tEquityComponents=RetainedEarnings;\t\t4684000.0000\t\n',
 '0000028917-25-000032\tDividendsCommonStockCash\tus-gaap/2024\t20251031\t3\tUSD\t\t\t12511000.0000\t\n',
 '0000028917-25-000032\tDividendsCommonStockCash\tus-gaap/2024\t20251031\t3\tUSD\tEquityComponents=RetainedEarnings;\t\t12511000.0000\t\n',
 '0000028917-25-000032\tEarningsPerShareBasic\tus-gaap/2024\t20241031\t1\tUSD\t\t\t7.7300\t\n',
 '0000028917-25-000032\tEarningsPerShareBasic\tus-gaap/2024\t20241031\t3\tUSD\t\t\t23.4200\t\n',
 '0000028917-25-000032\tEarningsPerShareBasic\tus-gaap/2024\t20251031\t1\tUSD\t\t\t8.3100\t\n',
 '0000028917-25-000032\tEarningsPerShareBasic\tus-gaap/2024\t20251031\t3\tUSD\t\t\t23.3900\t\n',
 '0000028917-25-000032\tEarningsPerShareDiluted\tus-gaap/2024\t20241031\t1\tUSD\t\t\t7.7300\t\n',
 '0000028917-25-000032\tEarningsPerShareDiluted\tus-gaap/2024\t20241031\t3\tUSD\t\t\t23.4200\t\n',
 '0000028917-25-000032\tEarningsPerShareDiluted\tus-gaap/2024\t20251031\t1\tUSD\t\t\t8.3100\t\n',
 '0000028917-25-000032\tEarningsPerShareDiluted\tus-gaap/2024\t20251031\t3\tUSD\t\t\t23.3900\t\n',
 '0000028917-25-000032\tGainLossOnDisposalOfAssetsExcludingInsuranceGain\t0000028917-25-000032\t20241031\t3\tUSD\t\t\t451000.0000\t\n',
 '0000028917-25-000032\tGainLossOnDisposalOfAssetsExcludingInsuranceGain\t0000028917-25-000032\t20251031\t3\tUSD\t\t\t5477000.0000\t\n',
 '0000028917-25-000032\tGainLossOnDispositionOfAssets1\tus-gaap/2024\t20241031\t1\tUSD\t\t\t171000.0000\t\n',
 '0000028917-25-000032\tGainLossOnDispositionOfAssets1\tus-gaap/2024\t20241031\t3\tUSD\t\t\t451000.0000\t\n',
 '0000028917-25-000032\tGainLossOnDispositionOfAssets1\tus-gaap/2024\t20251031\t1\tUSD\t\t\t577000.0000\t\n',
 '0000028917-25-000032\tGainLossOnDispositionOfAssets1\tus-gaap/2024\t20251031\t3\tUSD\t\t\t5477000.0000\t\n',
 '0000028917-25-000032\tIncomeLossFromContinuingOperationsBeforeIncomeTaxesExtraordinaryItemsNoncontrollingInterest\tus-gaap/2024\t20241031\t1\tUSD\t\t\t162506000.0000\t\n',
 '0000028917-25-000032\tIncomeLossFromContinuingOperationsBeforeIncomeTaxesExtraordinaryItemsNoncontrollingInterest\tus-gaap/2024\t20241031\t1\tUSD\tBusinessSegments=ConstructionSegment;ConsolidationItems=OperatingSegments;\t\t2093000.0000\t\n',
 '0000028917-25-000032\tIncomeLossFromContinuingOperationsBeforeIncomeTaxesExtraordinaryItemsNoncontrollingInterest\tus-gaap/2024\t20241031\t1\tUSD\tBusinessSegments=RetailOperationsSegment;ConsolidationItems=OperatingSegments;\t\t160413000.0000\t\n',
 '0000028917-25-000032\tIncomeLossFromContinuingOperationsBeforeIncomeTaxesExtraordinaryItemsNoncontrollingInterest\tus-gaap/2024\t20241031\t3\tUSD\t\t\t494427000.0000\t\n',
 '0000028917-25-000032\tIncomeLossFromContinuingOperationsBeforeIncomeTaxesExtraordinaryItemsNoncontrollingInterest\tus-gaap/2024\t20241031\t3\tUSD\tBusinessSegments=ConstructionSegment;ConsolidationItems=OperatingSegments;\t\t1330000.0000\t\n',
 '0000028917-25-000032\tIncomeLossFromContinuingOperationsBeforeIncomeTaxesExtraordinaryItemsNoncontrollingInterest\tus-gaap/2024\t20241031\t3\tUSD\tBusinessSegments=RetailOperationsSegment;ConsolidationItems=OperatingSegments;\t\t493097000.0000\t\n',
 '0000028917-25-000032\tIncomeLossFromContinuingOperationsBeforeIncomeTaxesExtraordinaryItemsNoncontrollingInterest\tus-gaap/2024\t20251031\t1\tUSD\t\t\t168810000.0000\t\n',
 '0000028917-25-000032\tIncomeLossFromContinuingOperationsBeforeIncomeTaxesExtraordinaryItemsNoncontrollingInterest\tus-gaap/2024\t20251031\t1\tUSD\tBusinessSegments=ConstructionSegment;ConsolidationItems=OperatingSegments;\t\t954000.0000\t\n',
 '0000028917-25-000032\tIncomeLossFromContinuingOperationsBeforeIncomeTaxesExtraordinaryItemsNoncontrollingInterest\tus-gaap/2024\t20251031\t1\tUSD\tBusinessSegments=RetailOperationsSegment;ConsolidationItems=OperatingSegments;\t\t167856000.0000\t\n',
 '0000028917-25-000032\tIncomeLossFromContinuingOperationsBeforeIncomeTaxesExtraordinaryItemsNoncontrollingInterest\tus-gaap/2024\t20251031\t3\tUSD\t\t\t477092000.0000\t\n',
 '0000028917-25-000032\tIncomeLossFromContinuingOperationsBeforeIncomeTaxesExtraordinaryItemsNoncontrollingInterest\tus-gaap/2024\t20251031\t3\tUSD\tBusinessSegments=ConstructionSegment;ConsolidationItems=OperatingSegments;\t\t3120000.0000\t\n',
 '0000028917-25-000032\tIncomeLossFromContinuingOperationsBeforeIncomeTaxesExtraordinaryItemsNoncontrollingInterest\tus-gaap/2024\t20251031\t3\tUSD\tBusinessSegments=RetailOperationsSegment;ConsolidationItems=OperatingSegments;\t\t473972000.0000\t\n',
 '0000028917-25-000032\tIncomeTaxExpenseBenefit\tus-gaap/2024\t20241031\t1\tUSD\t\t\t37910000.0000\t\n',
 '0000028917-25-000032\tIncomeTaxExpenseBenefit\tus-gaap/2024\t20241031\t3\tUSD\t\t\t115310000.0000\t\n',
 '0000028917-25-000032\tIncomeTaxExpenseBenefit\tus-gaap/2024\t20251031\t1\tUSD\t\t\t39000000.0000\t\n',
 '0000028917-25-000032\tIncomeTaxExpenseBenefit\tus-gaap/2024\t20251031\t3\tUSD\t\t\t110630000.0000\t\n',
 '0000028917-25-000032\tIncreaseDecreaseInAccountsPayableAndOtherOperatingLiabilities\tus-gaap/2024\t20241031\t3\tUSD\t\t\t447635000.0000\t\n',
 '0000028917-25-000032\tIncreaseDecreaseInAccountsPayableAndOtherOperatingLiabilities\tus-gaap/2024\t20251031\t3\tUSD\t\t\t426139000.0000\t\n',
 '0000028917-25-000032\tIncreaseDecreaseInAccountsReceivable\tus-gaap/2024\t20241031\t3\tUSD\t\t\t1194000.0000\t\n',
 '0000028917-25-000032\tIncreaseDecreaseInAccountsReceivable\tus-gaap/2024\t20251031\t3\tUSD\t\t\t-10799000.0000\t\n',
 '0000028917-25-000032\tIncreaseDecreaseInAccruedIncomeTaxesIncludingDeferredTaxLiabilities\t0000028917-25-000032\t20241031\t3\tUSD\t\t\t-24802000.0000\t\n',
 '0000028917-25-000032\tIncreaseDecreaseInAccruedIncomeTaxesIncludingDeferredTaxLiabilities\t0000028917-25-000032\t20251031\t3\tUSD\t\t\t101767000.0000\t\n',
 '0000028917-25-000032\tIncreaseDecreaseInOtherCurrentAssets\tus-gaap/2024\t20241031\t3\tUSD\t\t\t-9820000.0000\t\n',
 '0000028917-25-000032\tIncreaseDecreaseInOtherCurrentAssets\tus-gaap/2024\t20251031\t3\tUSD\t\t\t-22518000.0000\t\n',
 '0000028917-25-000032\tIncreaseDecreaseInOtherNoncurrentAssets\tus-gaap/2024\t20241031\t3\tUSD\t\t\t1037000.0000\t\n',
 '0000028917-25-000032\tIncreaseDecreaseInOtherNoncurrentAssets\tus-gaap/2024\t20251031\t3\tUSD\t\t\t-1992000.0000\t\n',
 '0000028917-25-000032\tIncreaseDecreaseInRetailRelatedInventories\tus-gaap/2024\t20241031\t3\tUSD\t\t\t588218000.0000\t\n',
 '0000028917-25-000032\tIncreaseDecreaseInRetailRelatedInventories\tus-gaap/2024\t20251031\t3\tUSD\t\t\t546024000.0000\t\n',
 '0000028917-25-000032\tInvestmentAndDebtInterestIncomeExpenseNet\t0000028917-25-000032\t20241031\t1\tUSD\t\t\t4478000.0000\t\n',
 '0000028917-25-000032\tInvestmentAndDebtInterestIncomeExpenseNet\t0000028917-25-000032\t20241031\t3\tUSD\t\t\t11944000.0000\t\n',
 '0000028917-25-000032\tInvestmentAndDebtInterestIncomeExpenseNet\t0000028917-25-000032\t20251031\t1\tUSD\t\t\t3076000.0000\t\n',
 '0000028917-25-000032\tInvestmentAndDebtInterestIncomeExpenseNet\t0000028917-25-000032\t20251031\t3\tUSD\t\t\t5355000.0000\t\n',
 '0000028917-25-000032\tJuniorSubordinatedDebentureOwedToUnconsolidatedSubsidiaryTrustNoncurrent\tus-gaap/2024\t20241031\t0\tUSD\t\t\t200000000.0000\t\n',

In [37]:
d[0]

'adsh\ttag\tversion\tddate\tqtrs\tuom\tsegments\tcoreg\tvalue\tfootnote\n'

In [38]:
rec = pd.DataFrame([r.split('\t') for r in d0], columns=d[0].split('\t'))
print(rec.shape)
rec[:10]

(348, 10)

,adsh,tag,version,ddate,qtrs,uom,segments,coreg,value,footnote\n
0,0000028917-25-000032,AccountsPayableAndAccruedLiabilitiesCurrent,us-gaap/2024,20241031,0,USD,,,1214982000.0000,\n
1,0000028917-25-000032,AccountsPayableAndAccruedLiabilitiesCurrent,us-gaap/2024,20250131,0,USD,,,795023000.0000,\n
2,0000028917-25-000032,AccountsPayableAndAccruedLiabilitiesCurrent,us-gaap/2024,20251031,0,USD,,,1213976000.0000,\n
3,0000028917-25-000032,AccountsReceivableNetCurrent,us-gaap/2024,20241031,0,USD,,,61741000.0000,\n
4,0000028917-25-000032,AccountsReceivableNetCurrent,us-gaap/2024,20250131,0,USD,,,55700000.0000,\n
5,0000028917-25-000032,AccountsReceivableNetCurrent,us-gaap/2024,20251031,0,USD,,,44901000.0000,\n
6,0000028917-25-000032,AccruedIncomeTaxesCurrent,us-gaap/2024,20241031,0,USD,,,10030000.0000,\n
7,0000028917-25-000032,AccruedIncomeTaxesCurrent,us-gaap/2024,20250131,0,USD,,,28472000.0000,\n
8,0000028917-25-000032,AccruedIncomeTaxesCurrent,us-gaap/2024,20251031,0,USD,,,125443000.0000,\n
9,0000028917-25-000032,AccruedTreasuryStockPurchases,0000028917-25-000032,20241031,3,USD,,,3053000.0000,\n

#

In [39]:
from collections import Counter

print(Counter(rec['adsh']).most_common())

print(Counter(rec['ddate']).most_common())
print()
print(rec.shape, len(Counter(rec['tag'])), Counter(rec['uom']),Counter(rec['qtrs']))
print()

target_date = ['20251031','20240131'][0]
rec2020 = rec[rec['ddate'] == target_date]

print(rec2020.shape, len(Counter(rec2020['tag'])), Counter(rec2020['uom']),Counter(rec2020['qtrs']))
display(rec2020)

Counter(rec2020['ddate']), Counter(rec2020['uom']),Counter(rec2020['qtrs'])

[('0000028917-25-000032', 348)]
[('20251031', 148), ('20241031', 145), ('20250131', 34), ('20240131', 7), ('20240731', 6), ('20250731', 6), ('20251130', 2)]

(348, 10) 82 Counter({'USD': 343, 'shares': 5}) Counter({'3': 139, '0': 130, '1': 79})

(148, 10) 82 Counter({'USD': 146, 'shares': 2}) Counter({'3': 71, '0': 39, '1': 38})

,adsh,tag,version,ddate,qtrs,uom,segments,coreg,value,footnote\n
2,0000028917-25-000032,AccountsPayableAndAccruedLiabilitiesCurrent,us-gaap/2024,20251031,0,USD,,,1213976000.0000,\n
5,0000028917-25-000032,AccountsReceivableNetCurrent,us-gaap/2024,20251031,0,USD,,,44901000.0000,\n
8,0000028917-25-000032,AccruedIncomeTaxesCurrent,us-gaap/2024,20251031,0,USD,,,125443000.0000,\n
10,0000028917-25-000032,AccruedTreasuryStockPurchases,0000028917-25-000032,20251031,3,USD,,,1064000.0000,\n
13,0000028917-25-000032,AccumulatedDepreciationDepletionAndAmortizationPropertyPlantAndEquipment,us-gaap/2024,20251031,0,USD,,,2882759000.0000,\n
...,...,...,...,...,...,...,...,...,...,...
337,0000028917-25-000032,TreasuryStockCommonValue,us-gaap/2024,20251031,0,USD,,,5463622000.0000,\n
342,0000028917-25-000032,TreasuryStockCommonValueAcquiredCostMethodIncludingExciseTax,0000028917-25-000032,20251031,3,USD,,,108820000.0000,\n
343,0000028917-25-000032,TreasuryStockCommonValueAcquiredCostMethodIncludingExciseTax,0000028917-25-000032,20251031,3,USD,EquityComponents=TreasuryStockCommon;,,108820000.0000,\n
346,0000028917-25-000032,TreasuryStockSharesAcquired,us-gaap/2024,20251031,3,shares,,,300013.0000,\n
347,0000028917-25-000032,UnsecuredDebtCurrent,us-gaap/2024,20251031,0,USD,,,96000000.0000,\n

(Counter({'20251031': 148}),
 Counter({'USD': 146, 'shares': 2}),
 Counter({'3': 71, '0': 39, '1': 38}))

In [40]:
pd.set_option('max_colwidth',100)
rec2020.iloc[[i for i,r in enumerate(rec2020['tag']) if search('Revenue', r)],[1,3,5,6,7]]

,tag,ddate,uom,segments,coreg
63,CostOfRevenue,20251031,USD,,
64,CostOfRevenue,20251031,USD,BusinessSegments=ConstructionSegment;ConsolidationItems=OperatingSegments;,
65,CostOfRevenue,20251031,USD,BusinessSegments=RetailOperationsSegment;ConsolidationItems=OperatingSegments;,
66,CostOfRevenue,20251031,USD,,
67,CostOfRevenue,20251031,USD,BusinessSegments=ConstructionSegment;ConsolidationItems=OperatingSegments;,
68,CostOfRevenue,20251031,USD,BusinessSegments=RetailOperationsSegment;ConsolidationItems=OperatingSegments;,
255,RevenueFromContractWithCustomerExcludingAssessedTax,20251031,USD,,
256,RevenueFromContractWithCustomerExcludingAssessedTax,20251031,USD,BusinessSegments=ConstructionSegment;ConsolidationItems=OperatingSegments;,
257,RevenueFromContractWithCustomerExcludingAssessedTax,20251031,USD,BusinessSegments=RetailOperationsSegment;ConsolidationItems=OperatingSegments;,
258,RevenueFromContractWithCustomerExcludingAssessedTax,20251031,USD,,
259,RevenueFromContractWithCustomerExcludingAssessedTax,20251031,USD,BusinessSegments=ConstructionSegment;ConsolidationItems=OperatingSegments;,
260,RevenueFromContractWithCustomerExcludingAssessedTax,20251031,USD,BusinessSegments=RetailOperationsSegment;ConsolidationItems=OperatingSegments;,
267,Revenues,20251031,USD,,
268,Revenues,20251031,USD,BusinessSegments=ConstructionSegment;ConsolidationItems=OperatingSegments;,
269,Revenues,20251031,USD,BusinessSegments=RetailOperationsSegment;ConsolidationItems=OperatingSegments;,
270,Revenues,20251031,USD,,
271,Revenues,20251031,USD,BusinessSegments=ConstructionSegment;ConsolidationItems=OperatingSegments;,
272,Revenues,20251031,USD,BusinessSegments=RetailOperationsSegment;ConsolidationItems=OperatingSegments;,

# Altman’s z-score 
## X1=working capital/total assets
## X2=retained earnings/total assets
## X3=earning before interest & taxes/total assets
## X4=market value of equity/book value of liabilities
## X5=sales/total assets

#### Unlikely to default if
$Z = 1.2X_1 + 1.4X_2 + 3.3X_3 + 0.6X_4 + 0.999 > 3$
#### Z < 1.8 very high default probability

In [41]:
stats = dict([(t,float(v+'0')) for t,v in zip(rec2020['tag'], rec2020['value'])])

X1 = (stats['AssetsCurrent'] - stats['LiabilitiesCurrent']) / stats['Assets']
X2 = stats['RetainedEarningsAccumulatedDeficit'] / stats['Assets']
X3 = stats['ComprehensiveIncomeNetOfTax'] / stats['Assets']
X4 = stats['CommonStockValue'] / stats['LiabilitiesCurrent']
X5 = stats['ProceedsFromSalesOfAssetsInvestingActivities'] / stats['Assets']
X5 = stats['Revenues'] / stats['Assets']

for s in "X1,X2,X3,X4,X5".split(','):
    print(f"{s} = {eval(s):6.3f}")

altman_z = 1.2 * 𝑋1 + 1.4 * 𝑋2 + 3.3 * 𝑋3 + 0.6 * 𝑋4 + 0.999 * X5

print(f"\nZ = {altman_z:0.3f}\n")

for c,text in [(1.8, 'very high default prob'),(3.0,'"grey zone"'), (float('inf'),'unlikely to default')]:
    if altman_z < c:
        print(f"altman z = {altman_z:0.3f}, {text}")
        break

X1 =  0.408
X2 =  1.558
X3 =  0.087
X4 =  0.001
X5 =  1.036

Z = 3.995

altman z = 3.995, unlikely to default

debt = 'LongTermDebtNoncurrent'
earnings = 'Billingsinexcessofcostsandestimatedearningsonuncompletedcontractsconstructionsegment'
retained earnings ='RetainedEarningsAccumulatedDeficit'
stockvalue = 'StockholdersEquity'

Earnings Before Interest and Taxes = ComprehensiveIncomeNetOfTax

Billingsinexcessofcostsandestimatedearningsonuncompletedcontractsconstructionsegment - 

Working capital is defined as the difference between current assets and
current liabilities. AssetsCurrent - LiabilitiesCurrent

CommonStockValue
LiabilitiesAndStockholdersEquity	

x1: 'LiabilitiesAndStockholdersEquity', 'Assets'
x2: 'RetainedEarningsAccumulatedDeficit	', 'Assets'